# ci_intelligence.py
import argparse
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

def parse_coverage(coverage_file: Path) -> float:
    """
    Parse coverage.xml generated by pytest-cov.
    Returns coverage as a float from 0 to 1.
    """
    if not coverage_file.exists():
        print(f"Coverage file {coverage_file} not found", file=sys.stderr)
        return 0.0

    tree = ET.parse(coverage_file)
    root = tree.getroot()

    # For coverage.py XML format, root has 'line-rate'
    line_rate = root.attrib.get("line-rate")
    if line_rate is None:
        print("line-rate attribute not found in coverage XML", file=sys.stderr)
        return 0.0

    try:
        return float(line_rate)
    except ValueError:
        return 0.0


def compute_intelligence(coverage: float, lint_score: float | None = None) -> dict:
    """
    Compute a simple 'intelligence' decision:
    - Score = weighted combination of coverage and (optional) lint score.
    - Deploy if score >= 0.8 and coverage >= 0.75
    """
    weight_coverage = 0.7
    weight_lint = 0.3

    if lint_score is None:
        # Just use coverage if lint score not provided
        score = coverage
    else:
        score = weight_coverage * coverage + weight_lint * lint_score

    deploy = (score >= 0.8) and (coverage >= 0.75)

    return {
        "coverage": coverage,
        "lint_score": lint_score,
        "score": score,
        "deploy": deploy,
        "reason": (
            "Score and coverage thresholds met"
            if deploy
            else "Score or coverage threshold not met"
        ),
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--coverage-file", type=str, required=True)
    parser.add_argument("--lint-score", type=float, required=False)
    parser.add_argument("--output-file", type=str, required=True)
    args = parser.parse_args()

    coverage = parse_coverage(Path(args.coverage_file))
    lint_score = args.lint_score

    result = compute_intelligence(coverage=coverage, lint_score=lint_score)

    # Write JSON output for GitHub Actions
    with open(args.output_file, "w", encoding="utf-8") as f:
        json.dump(result, f)

    # Also print a human-friendly log
    print("Intelligence result:")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
